#+export_file_name: index
#+options: broken-links:t
# (ss-toggle-markdown-export-on-save)
# date-added:

# add filename after "imagefile"
#+macro: imagefile understanding.webp

#+begin_export md
---
title: "Understanding the Significance of Hexose Phosphorylation in the Glycolysis Pathway Based on Quantum Chemistry and Molecular Dynamics Simulations: A Computational Course for Undergraduate Students with a Life Science Background"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
license: "©2025 American Chemical Society and Division of Chemical Education, Inc."
#license: "CC BY-NC-SA"
#draft: true
#date-modified:
date: 2025-10-28
categories: [course design, computational, mol dynamics]
keywords: physical chemistry teaching, physical chemistry education, teaching resources,     Upper-Division Undergraduate, Biochemistry, Computer-Based Learning, Glycolysis, Quantum Chemistry, Molecular Dynamics Simulations, Covalent Bonding, Molecular Recognition
#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
Computational chemistry is increasingly employed across diverse biological research domains, and proficiency in quantum chemistry and molecular dynamics software is essential for biochemistry education. Integrating computational chemistry into the life sciences curriculum enhances students’ understanding of its practical applications. However, existing pedagogical approaches often emphasize molecular modeling and dynamics simulations with a limited focus on developing quantum chemistry skills. Grounded in a problem-based learning framework, this study begins by examining the role of hexose phosphorylation within the glycolysis module of biochemistry courses. It introduces a comprehensive training program encompassing quantum chemistry and molecular dynamics simulation. Through this curriculum, students perform bond energy analyses using quantum mechanics and assess enzyme–substrate binding energies via molecular mechanics. In mastering foundational computational techniques, they gain deeper insight into the functional relevance of hexose phosphorylation in substrate recognition by aldolase and develop a robust appreciation for the broader applicability of computational chemistry in life science research.
* Reference
Nan Wu, et. al., J. Chem. Ed., 2025, [[https://doi.org/10.1021/acs.jchemed.5c00571][doi.org/10.1021/acs.jchemed.5c00571]]

* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
