#+export_file_name: community
# (ss-toggle-markdown-export-on-save)
# date-added:

#+begin_export md
---
title: "Communities"
---
#+end_export
* POGIL Physical Chemistry Laboratory
POGIL-PCL is a group of several dozen physical chemists working together to make the physical chemistry lab course and engaging and meaningful learning experience. Through this work an enthusiastic community arose. POGIL-PCL organizes online and in-person workshops, a reading club (with synchronous online discussions), a newsletter, and laboratory development meetings. https://www.pogilpcl.org/get-connected


* LABSIP
LABSIP (Lowering Access Barriers to Success in Physical Chemistry) is a collaborative project led by eleven physical chemistry instructors and funded initially by Research Corporation for Science Advancement. Our short-term goal is community engagement around new directions in Physical Chemistry instruction, with a longer-term goal of providing guidelines and resources towards a more inclusive, dynamic, and current physical chemistry curriculum.
https://labsip.org/

* Engaging Students in Physical Chemistry
The idea for this Google group began in the Engaging Students in Physical Chemistry symposium at the 2014 Biennial Conference on Chemical Education.  This idea was revived at the 2016 BCCE.  I'd like to make this group useful for you.  Thanks!  --Craig Teague, Cornell College, Mount Vernon IA
https://groups.google.com/g/engaging-students-in-physical-chemistry (google account required)
