#+export_file_name: events
# (ss-toggle-markdown-export-on-save)
# date-added:

#+begin_export md
---
title: "Events"
---
#+end_export
Please send your event details to ssinglet@coe.edu
** POGIL-PCL Zoom Workshop
The POGIL-PCL team will host a moderated zoom workshop November 2 & 9, 2023, from 7pm-9pm Eastern time. We will work through the experiment, "What can an IR spectrum tell you about a molecule?" More details about the experiment: https://chemistry.coe.edu/piper/posts/gas-phase-ir-pcl/

Teams of participants will work through the experiment and have time to discuss the experiment. Moderators will do regular check-ins and be available for questions, and they will lead discussions on POGIL-PCL and facilitation.

Please complete this form, https://forms.gle/8YmUuKTEHXpsPUjy6 to let us know your interest in this workshop.

To participate fully, you should have a computer with audio and video capability as well as access to Google drive. To get the most out of the experience, participants will also complete pre-experiment questions outside of the workshop time.

This experiment was recently highlighted in the special issue of J. Chem. Educ. last December: https://doi.org/10.1021/acs.jchemed.2c00314

* Past events :noexport:
** MOLSSI QCArchive Webinar
Computational chemists: MolSSI is having a webinar on Thursday, Sept. 21, 2023 introducing their new QCArchive Software.  QCArchive is a MolSSI open-source software product that helps you run and archive results for QM calculations.  The webinar is totally introductory, so no experience with QCArchive is needed to attend.  Find out more at https://molssi.org/introduction-to-qcarchive-free-online-webinar/

** LABSIP event at August ACS meeting
Informal coffee hour on Monday August 14, 2023 from about 9:15-11:15 am PDT in the Moscone Center South, 200 level near PHYS and COMP talks.  Please come say hi!  Bring friends! Coffee and snacks will be provided.
