#+export_file_name: index
#+options: broken-links:t
# (ss-toggle-markdown-export-on-save)
# date-added:
#+MACRO: imagefile photochemistry.webp

#+begin_export md
---
title: "A Six-Week Student-Led Project Designed to Provide Insight into Modern Photochemistry Research"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
#license: "©2025 American Chemical Society and Division of Chemical Education, Inc."
license: "CC BY"
#draft: true
#date-modified:
date: 2025-03-15
categories: [spectroscopy, computational]
keywords: physical chemistry teaching, physical chemistry education, teaching resources, plotting, computational chemistry, photochemistry

#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
An advanced chemistry laboratory project has been developed to introduce final year undergraduate students to organic photocatalyst design using benzo[c][1,2,5]thiadiazole (BTZ) photocatalysts, prepared via a single Suzuki-Miyaura cross-coupling from cheap starting materials, as the example. This project took on a research lab style structure, and over the course of 6 weeks students were tasked to (1) synthesize and study the photophysical properties of three BTZ-based photocatalysts; (2) apply the BTZ photocatalysts to a test photoredox reaction using cheap home-built LEDs, and (3) perform rudimentary computational calculations to rationalize key experimental results.

* Reference
Dominic Taylor, Leonardo Amicosante, Luize M. Luse, Martin R. S. McCoustra, Lee McMahon, Scott J. Dalgarno, Filipe Vilela, /J. Chem. Ed./, 2025, [[https://doi.org/10.1021/acs.jchemed.4c01241][doi.org/10.1021/acs.jchemed.4c01241]]

* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
