#+export_file_name: index
#+options: broken-links:t
# (ss-toggle-markdown-export-on-save)
# date-added:

# add filename after "imagefile"
#+macro: imagefile steeping-tea.webp

#+begin_export md
---
title: "The Art of Steeping a Cup of Tea: Exploring Temperature Effect on Caffeine Release Kinetics Using 1H NMR in Undergraduate Laboratories"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
#license: "©2025 American Chemical Society and Division of Chemical Education, Inc."
#license: "CC BY-NC-SA"
#draft: true
#date-modified:
date: 2025-10-28
categories: [nmr, kinetics, lab]
keywords: physical chemistry teaching, physical chemistry education, teaching resources, kinetics, nuclear magnetic resonance, laboratory experiment
#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
This study reports an undergraduate laboratory experiment that explores the temperature-dependent kinetics of caffeine release during tea steeping by using quantitative 1H NMR spectroscopy with a water suppression pulse sequence. Designed for introductory organic chemistry laboratory courses, the experiment emphasizes the real-world application of NMR-based organic analysis in aqueous systems without using organic solvents. Students steeped tea samples at 20 °C, 50 °C, and 100 °C and collected tea aliquots over 8 min to quantify the caffeine release. Their results consistently showed the highest release rate at 100 °C, with lower rates at 20 and 50 °C. While the caffeine concentration in tea increased during the initial steeping time, it plateaued toward the end of the steeping at high temperatures. Arrhenius plots of kinetics data generated by students yielded apparent activation energy values close to the anticipated value of 22.6 ± 2.5 kJ/mol obtained from the authors’ benchmark experiments. This experiment design reinforces key concepts in chemical kinetics and quantitative NMR, providing a green approach to learning that connects textbook principles to use-inspired activities. The pedagogical activities also support skill-building in data analysis, spectroscopy, and green chemistry.
* Reference
Priya Boora, Leah C. Zohner, Martha D. Morton, Chin Li Cheung, J. Chem. Ed., 2025, [[https://doi.org/10.1021/acs.jchemed.5c00504][doi.org/10.1021/acs.jchemed.5c00504]]
* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
