#+export_file_name: index
#+options: broken-links:t
# (ss-toggle-markdown-export-on-save)
# date-added:

# add filename after "imagefile"
#+macro: imagefile fluid.gif

#+begin_export md
---
title: "Fluid Interface Thermodynamics Software: From Theory to Instruction"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
license: "©2025 American Chemical Society and Division of Chemical Education, Inc."
#license: "CC BY-NC-SA"
#draft: true
#date-modified:
date: 2025-07-28  
categories: [thermodynamics]
keywords: physical chemistry teaching, physical chemistry education, teaching resources, fluid interface, thermodynamics
#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
The structure and properties of solid–liquid interfaces have long been central topics in interfacial science, and various theoretical methods have been developed to accurately describe the species therein. However, many of these approaches remain complex and difficult to implement in educational contexts. Herein, we present a web-based software platform for fluid interface thermodynamics that features a user-friendly graphical interface specifically designed for educational use. The platform integrates several widely used computational models, including Poisson–Boltzmann, Poisson–Nernst–Planck, and classical density functional theory. This study aims to support the teaching and learning of interfacial phenomena by allowing students, particularly those without programming experience, to effectively interact with and explore fluid interface simulations.

* Reference
Q. Wang, et al, J. Chem. Educ. 2025, 102, 8, 3623–3630, [[https://doi.org/10.1021/acs.jchemed.5c00084][doi.org/10.1021/acs.jchemed.5c00084]]
* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
