#+export_file_name: index
#+options: broken-links:t
# (ss-toggle-markdown-export-on-save)
# date-added:

# add filename after "imagefile"
#+macro: imagefile gentle.gif

#+begin_export md
---
title: "A Gentle Introduction to Machine Learning for Chemists: An Undergraduate Workshop Using Python Notebooks for Visualization, Data Processing, Analysis, and Modeling"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
license: "©2021 American Chemical Society and Division of Chemical Education, Inc."
#license: "CC BY-NC-SA"
#draft: true
#date-modified:
date: 2023-10-26
categories: [ai-ml, python]
keywords: physical chemistry teaching, physical chemistry education, teaching resources, artificial intelligence, llm, gpt, python, machine learning, chemist
#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
Machine learning, a subdomain of artificial intelligence, is a widespread technology that is molding how chemists interact with data. Therefore, it is a relevant skill to incorporate into the toolbox of any chemistry student. This work presents a workshop that introduces machine learning for chemistry students based on a set of Python notebooks and assignments. Python, one of the most popular programming languages, is open source, free to use, and has plenty of learning resources. The workshop is designed for students without previous experience in programming, and it aims for a deeper understanding of the complexity of concepts in programming and machine learning. The examples used correspond to real data from physicochemical characterizations of wine, a content that is of interest for students. The contents of the workshop are introduction to Python, basic statistics, data visualization, and dimension reduction, classification, and regression.
* Reference
Lafuente, et. al., /J. Chem. Educ.. 2021, 98, 9, 2892–2898, [[https://doi.org/10.1021/acs.jchemed.1c00142][doi.org/10.1021/acs.jchemed.1c00142]]
* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
