#+export_file_name: index
#+options: broken-links:t
# (ss-toggle-markdown-export-on-save)
# date-added:

# add filename after "imagefile"
#+macro: imagefile nmr.webp

#+begin_export md
---
title: "Simple Web-Based Interactive Visualizations to Illustrate and Explore Concepts in NMR Spectroscopy"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
#license: "©2025 American Chemical Society and Division of Chemical Education, Inc."
license: "CC BY"
#draft: true
#date-modified:
date: 2025-10-01
categories: [nmr, website]
keywords: physical chemistry teaching, physical chemistry education, teaching resources, nmr, nuclear magnetic resonance, visualization, simulation
#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
The interpretation of NMR spectra is a fundamental skill for chemists. Multiple strategies and resources support the teaching and learning of NMR spectroscopy, such as worked examples and question banks. A challenge in NMR spectral interpretation is cognitive overload, especially for beginners who must assimilate new information alongside existing knowledge of molecular structure. A useful strategy is to provide visualizations of spectra. However, existing software solutions (often requiring purchase or installation) can be convoluted, with excess features for a beginner and a focus on organic molecules and 1H/13C NMR spectra. This work provides freely accessible, web-based interactive visualizations to support the teaching and learning of NMR spectroscopy (https://chem-ed.github.io/NMR/). These are designed to be simple, focus on defined concepts with minimal distractions, and increase interactivity to enhance engagement. These cover fundamental topics such as chemical shift, multiplicity, and J coupling constants, of use to learners relatively new to NMR spectral interpretation, as well as more complex areas like decoupling and successive coupling. A notable feature is the ability to consider coupling to quadrupolar nuclei (I > 1/2) and isotopes with <100% natural abundance forming satellite signals─concepts often overlooked but essential to inorganic chemistry and multinuclear NMR spectroscopy, providing resources for more advanced learners.
* Reference
https://chem-ed.github.io/NMR/

Euan D. Doidge, /J. Chem. Educ./, 2025, [[https://doi.org/10.1021/acs.jchemed.5c00985][doi.org/10.1021/acs.jchemed.5c00985]]
* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
