#+export_file_name: index
#+options: broken-links:t
# (ss-toggle-markdown-export-on-save)
# date-added:

# add filename after "imagefile"
#+macro: imagefile integrating-spectroscopy.webp

#+begin_export md
---
title: "Integrating Spectroscopy, Thermodynamics, and Computational Chemistry in the Undergraduate Laboratory by Studying Globin–Nitrite Interactions"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
license: "©2025 American Chemical Society and Division of Chemical Education, Inc."
#license: "CC BY-NC-SA"
#draft: true
#date-modified:
date: 2025-10-05
categories: [spectroscopy, computational, thermo]
keywords: physical chemistry teaching, physical chemistry education, teaching resources, thermodynamics, computational chemistry, spectroscopy
#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
A comprehensive laboratory experiment where students explore the thermodynamics of small molecule binding to myoglobin (Mb) and the spectroscopic changes associated during the event was developed for the upper-division physical chemistry laboratory. This provides students with a hands-on approach toward understanding protein–ligand interactions and binding equilibria using temperature-dependent UV–vis spectroscopy. Further, this allows them to investigate key concepts of thermodynamic variables such as entropy, enthalpy, and Gibbs free energy in a biological context, bridging theoretical knowledge with practical applications. Computational simulations on NO_{2}^{–} and visualization of the Fe^{III}–NO_{2}^{–} interaction using known crystal structures of wild-type Mb and variant H64V Mb, as well as model [Mb^{III}–NO_{2}^{–}] complexes, further solidified their understanding of the vibrational motions of nitrite, its binding mechanism to the iron center, and the influence of the protein structure in stabilizing the ligand–metal interaction. The experiment can be achieved in two 3-hour lab periods.

* Reference
Mary Grace I. Galinato, Ashlee M. Harwood, Allyson Ray, Emily P. Kiker, /J. Chem. Educ./ 2025, [[https://doi.org/10.1021/acs.jchemed.5c00686][doi.org/10.1021/acs.jchemed.5c00686]]
* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
