#+export_file_name: index
#+options: broken-links:t toc:nil
# (ss-toggle-markdown-export-on-save)
# date-added:

# add filename after "imagefile"
#+macro: imagefile wastewater.gif

#+begin_export md
---
title: "Integrating physical chemistry and sustainability: an educational study of linear and non-linear adsorption isotherms using chitosan in wastewater remediation"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
#license: "©2026 American Chemical Society and Division of Chemical Education, Inc."
license: "CC BY"
#draft: true
#date-modified:
date: 2026-04-01
categories: [lab, environment, thermo]
keywords: physical chemistry teaching, physical chemistry education, teaching resources, sustainability, adsorption isotherms, wastewater, learning, student, experiment
#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
Water scarcity is an escalating global challenge. Addressing this issue requires not only technological solutions but also educational strategies that integrate sustainability into chemistry curricula. Herein, we report the design and implementation of a two-session undergraduate Physical Chemistry laboratory experiment focused on the adsorption of the synthetic food dye tartrazine onto chitosan, a sustainable biopolymer. The experiment contextualizes adsorption thermodynamics within wastewater remediation and the United Nations Sustainable Development Goals, particularly SDG 6 (Clean Water and Sanitation). Students investigated adsorption equilibrium by measuring tartrazine uptake over a range of initial concentrations at two temperatures (25 and 50 °C). Equilibrium data were analyzed using both linear and non-linear forms of the Temkin adsorption isotherm, enabling a critical comparison of modeling approaches commonly used in the adsorption literature. Apparent thermodynamic parameters (ΔH_{app}, ΔG_{app}, and ΔS_{app}) are derived from the temperature dependence of the Temkin isotherm constant, providing a quantitative link between experimental data and thermodynamic theory. This laboratory activity emphasizes the physical meaning and limitations of linearized models while introducing non-linear regression methods that are often underrepresented in undergraduate instruction.
* Reference
Tanishka Chauhana, Santunu Baruab and Alexandre H. Pinto, /RSC Sustainability/, 2026, [[https://doi.org/10.1039/D5SU00960J][doi.org/10.1039/D5SU00960J]]

* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
