#+export_file_name: index
#+options: broken-links:t
# (ss-toggle-markdown-export-on-save)
# date-added:

# add filename after "imagefile"
#+macro: imagefile spontaneous.webp

#+begin_export md
---
title: "Pedagogical Revision of Spontaneous Emission and Photons"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
license: "©2025 American Chemical Society and Division of Chemical Education, Inc."
#license: "CC BY-NC-SA"
#draft: true
#date-modified:
date: 2025-05-01
categories: [article, quantum]
keywords: physical chemistry teaching, physical chemistry education, teaching resources, Mathematical methods, Physical and chemical processes
#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
This article provides teaching material on classical and quantum electromagnetic field theory for undergraduate and graduate chemistry students. It focuses on the concepts of spontaneous emission and the photon as explained by quantum electromagnetic field theory. In general chemistry classrooms, these concepts are introduced early on using the well-known Jablonski diagram. However, we argue that the current approach to teaching spontaneous emission and the photon in chemistry needs to be re-evaluated in light of insights from quantum electromagnetic field theory. This article presents a revised proposal for teaching these topics.

* Reference
Atanu Bhattacharya, Elliot R. Bernstein, Gurazada Ravi Kumar, Arpan Chakraborty, Jayatirtha Mangalvedekar, Jayanta Ghosh, Moulinath Roy, /J. Chem. Educ./, 2025, [[https://doi.org/10.1021/acs.jchemed.4c01030][doi.org/10.1021/acs.jchemed.4c01030]]

* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
