#+export_file_name: index
#+options: broken-links:t
# (ss-toggle-markdown-export-on-save)
# date-added:

# add filename after "imagefile"
#+macro: imagefile ruby.webp

#+begin_export md
---
title: "Visualizing Ruby Emission Decay Lifetime with Slow-Motion Digital Cameras: A Demonstration for Students"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
license: "©2025 American Chemical Society and Division of Chemical Education, Inc."
#license: "CC BY-NC-SA"
#draft: true
#date-modified:
date: 2025-05-01
categories: [lab, kinetics, spectroscopy]
keywords: physical chemistry teaching, physical chemistry education, teaching resources
#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
This short article describes a safe way of observing the emission decay from a ruby crystal using a photographic flash. This demonstration does not require the use of lasers and can be easily and safely performed in a classroom or a home setting. The ruby sample was optically excited with a short-duration photographic flash, and the subsequent relaxation of the excited state population through intermediate metastable states was monitored using three different types of slow-motion digital cameras. Monitoring the recorded video frames allowed visualization of the population decay kinetics. In addition, the measurement of frame intensities allowed for the computation of the excited state lifetime and decay rate constant. This demonstration can be utilized in several different chemical education courses at the advanced high school or undergraduate level, for example, in the courses that involve concepts related to photochemical reaction kinetics, flash photolysis, lasers, etc.

* Reference
Dinesh Dhankhar, /J. Chem. Educ./, 2025, [[https://doi.org/10.1021/acs.jchemed.4c01529][doi.org/10.1021/acs.jchemed.4c01529]] 
* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
