#+export_file_name: index
#+options: broken-links:t
# (ss-toggle-markdown-export-on-save)
# date-added:

# add filename after "imagefile"
#+macro: imagefile ensuring.gif

#+begin_export md
---
title: "Ensuring We Assess What We Value in Laboratory Work"
## https://quarto.org/docs/journals/authors.html
#author:
#  - name: ""
#    affiliations:
#     - name: ""
#license: "©2025 American Chemical Society and Division of Chemical Education, Inc."
#license: "CC BY-NC-SA"
#draft: true
#date-modified:
date: 2025-04-07
categories: [article, course design, lab]
keywords: physical chemistry teaching, physical chemistry education, teaching resources, assessment, laboratory assessment
#+end_export
image: {{{imagefile}}}

@@html:---
<img src="@@{{{imagefile}}}@@html:" width="40%" align="right" style="padding: 10px 0px 0px 10px;"/>@@

# Abstract goes below this line.
Learning how to do chemistry is a valued goal for students undertaking laboratory work in university chemistry degrees; however, in many cases, it is not the student’s laboratory work that is assessed but a report that could just as easily be written using data supplied by the course coordinator. Building on recent work establishing the use of chemistry learning outcomes in course evaluations, a framework for evaluating what we assess in chemistry laboratory work was formulated and tested. Not surprisingly, application of the framework identified a lack of Direct Assessment of Practical Skills (DAPS), but its application can act as a catalyst for faculty to reflect on their assessments of laboratory work and, where necessary, implement in-lab assessments. Based on the Australian Chemistry Threshold Learning Outcomes, the chemistry practical learning outcomes within this framework can be easily aligned with course requirements in other regions (e.g., ACS Guidelines for Undergraduate Chemistry Programs or RSC Accreditation of degree programs), thus providing a universally applicable framework.

* Reference
Andrew Seen, /J. Chem. Educ./ 2025, 102, 5, 2172–2176, [[https://doi.org/10.1021/acs.jchemed.4c01407][doi.org/10.1021/acs.jchemed.4c01407]]
* Local variables :noexport:
# Local Variables:
# eval: (ss-markdown-export-on-save)
# End:
